Class {
	#name : 'ManifestAdventOfCode2025Tests',
	#superclass : 'PackageManifest',
	#category : 'AdventOfCode-2025-Tests-Manifest',
	#package : 'AdventOfCode-2025-Tests',
	#tag : 'Manifest'
}

{ #category : 'code-critics' }
ManifestAdventOfCode2025Tests class >> ruleLiteralArrayCharactersRuleV1FalsePositive [

	<ignoreForCoverage>
	^ #(#(#(#RGMethodDefinition #(#AOCGridTest #testGlyph #false)) #'2025-11-08T12:09:48.709913-07:00') )
]
